// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: messages.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const saveMessage = `-- name: SaveMessage :one
INSERT INTO messages (id, body, user_id, created_at, updated_at)
VALUES (gen_random_uuid(), $1, $2, now(), now())
returning id, body, user_id, created_at, updated_at
`

type SaveMessageParams struct {
	Body   string
	UserID uuid.UUID
}

func (q *Queries) SaveMessage(ctx context.Context, arg SaveMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, saveMessage, arg.Body, arg.UserID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Body,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
