// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Message struct {
	ID        uuid.UUID
	Body      string
	UserID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiredAt time.Time
	RevokedAt sql.NullTime
}

type User struct {
	ID           uuid.UUID
	Email        string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	HashPassword string
}
